---
- name: apache-ansible-playbook
  hosts: all
  become: true
  tasks:
  - name: instalar apache
    apt:
      name: apache2
      state: present
  - name: encender apache
    service:
      name: apache2
      state: started